#!/usr/bin/env python
# coding: utf-8

# In[ ]:





# In[86]:


from sklearn.preprocessing import LabelEncoder
import pandas as pd
df=pd.read_csv("D:/titanic.csv")
df=df.dropna()
df


# In[87]:


Le = LabelEncoder()
df["Sex"] = Le.fit_transform(df["Sex"])
df["Sex"].unique()


# In[88]:


y= df[["Survived"]]
x = df[["Fare","Age","Sex"]]
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x,y)
df.head()


# In[104]:


from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size =0.1)


# In[105]:


from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train,y_train)


# In[112]:


from sklearn.metrics import accuracy_score
y_predict = model.predict(x_test)
accuracy_score(y_predict,y_test)


# In[109]:


from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train,y_train)


# In[ ]:





# In[115]:


from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)


# In[116]:



y_predict = model.predict(x_test)
accuracy_score(y_predict,y_test)

